FROM php:7.4-cli
RUN apt update && apt install -y git unzip libpq-dev
RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql && \
  docker-php-ext-install pdo_pgsql pgsql
RUN docker-php-ext-install opcache

RUN php -r "copy('https://getcomposer.org/download/latest-stable/composer.phar', '/usr/local/bin/composer');" && chmod +x /usr/local/bin/composer

RUN cd /var/www/html && git clone --single-branch --depth=1 https://github.com/WordPress/WordPress .
COPY . /var/www/html/

RUN apt autoremove -y --purge git unzip && rm -rf /var/lib/apt/lists/*
WORKDIR /var/www/html
CMD php -S 0.0.0.0:80
